### ISSUE TITLE
Link to demo of checkbox broken

### ISSUE THREAD

**Issue by ccheever** [dropbox/dropbox-js#229]
The "See it in action here" link is broken.
https://dl-web.dropbox.com/spa/pjlfdak1tmznswp/checkbox.js/public/index.html

Once you log in (at least for me), it shows these errors:
https://www.dropbox.com/s/vdxrf68e49mrnqs/Screenshot%202015-06-16%2002.27.34.png?dl=0

https://www.dropbox.com/s/9xc70xups2a72j7/Screenshot%202015-06-16%2002.28.03.png?dl=0

**Comment by varenc** [comment]
hey there!

looks like a "?" was getting appended to the redirect_uri param on the OAuth page for some reason.  You were getting a 400 since it was an unrecognized redirect_uri.  The friendly error that explains this was hidden since that app is out of development mode. 

I updated the app to include this, though I'm still not exactly sure why the "?" is getting appended in the first place.  Works for now at least! :-)

**Comment by ccheever** [comment]
Thanks Chris!
